# .travis.yml
language: node_js
node_js:
  - "0.11"

before_script:
  - sudo ./dev/apt.postgresql.org.sh
  - sudo apt-get install -y curl build-essential git libpq-dev postgresql-9.3 postgresql-contrib-9.3 postgresql-server-dev-9.3 postgresql-plpython-9.3
  - grep -v 'max_locks_per_transaction = 200' /etc/postgresql/9.3/main/postgresql.conf && (sudo bash -c "echo 'max_locks_per_transaction = 200' >> /etc/postgresql/9.3/main/postgresql.conf" && sudo service postgresql restart)
  - sudo su postgres -c 'createuser -s root'
  - git clone https://github.com/theory/pgtap.git /tmp/pgtap
  - cd /tmp/pgtap
  - echo y | sudo perl -MCPAN -e 'install TAP::Parser::SourceHandler::pgTAP'
  - make
  - sudo make install
  - sudo make installcheck
  - sudo service postgresql restart
  - cp $TRAVIS_BUILD_DIR/dev/fbdev_config.sh.travis $TRAVIS_BUILD_DIR/dev/fbdev_config.sh
script: cd $TRAVIS_BUILD_DIR/dev  && ./fbdev test'
