# .travis.yml
before_script:
  - echo y | sudo perl -MCPAN -e 'install TAP::Parser::SourceHandler::pgTAP'
  # - sudo apt-get install tree curl build-essential git libpq-dev postgresql-9.3 postgresql-contrib-9.3 postgresql-server-dev-9.3 postgresql-plpython-9.3
  - sudo pg_ctlcluster 9.1 main stop
  - sudo pg_ctlcluster 9.3 main start
  - sudo pg_lsclusters
  - sudo bash -c "echo 'max_locks_per_transaction = 200' >> /etc/postgresql/9.3/main/postgresql.conf"
  - sudo service postgresql restart
  - sudo su postgres -c 'createuser -s root'
  - git clone https://github.com/theory/pgtap.git /tmp/pgtap
  - env PG_CONFIG=/etc/postgresql/9.3/main/postgresql.conf && export PERL5LIB=/home/travis/perl5/lib/perl5 && cd /tmp/pgtap && make && sudo make install
  - sudo service postgresql restart

script: export PERL5LIB=/home/travis/perl5/lib/perl5 && source /home/travis/.bashrc && cd $TRAVIS_BUILD_DIR/dev && ./fbdev -c fbdev_config.sh.travis test
