ALTER TABLE observation_sort ALTER COLUMN lower DROP NOT NULL;
ALTER TABLE observation_sort ALTER COLUMN upper DROP NOT NULL;
ALTER TABLE condition_sort ALTER COLUMN lower DROP NOT NULL;
ALTER TABLE condition_sort ALTER COLUMN upper DROP NOT NULL;
ALTER TABLE encounter_sort ALTER COLUMN lower DROP NOT NULL;
ALTER TABLE encounter_sort ALTER COLUMN upper DROP NOT NULL;
ALTER TABLE practitioner_sort ALTER COLUMN lower DROP NOT NULL;
ALTER TABLE practitioner_sort ALTER COLUMN upper DROP NOT NULL;
ALTER TABLE patient_sort ALTER COLUMN lower DROP NOT NULL;
ALTER TABLE patient_sort ALTER COLUMN upper DROP NOT NULL;
ALTER TABLE medication_sort ALTER COLUMN lower DROP NOT NULL;
ALTER TABLE medication_sort ALTER COLUMN upper DROP NOT NULL;
ALTER TABLE medicationstatement_sort ALTER COLUMN lower DROP NOT NULL;
ALTER TABLE medicationstatement_sort ALTER COLUMN upper DROP NOT NULL;
ALTER TABLE diagnosticreport_sort ALTER COLUMN lower DROP NOT NULL;
ALTER TABLE diagnosticreport_sort ALTER COLUMN upper DROP NOT NULL;
ALTER TABLE documentreference_sort ALTER COLUMN lower DROP NOT NULL;
ALTER TABLE documentreference_sort ALTER COLUMN upper DROP NOT NULL;
ALTER TABLE allergyintolerance_sort ALTER COLUMN lower DROP NOT NULL;
ALTER TABLE allergyintolerance_sort ALTER COLUMN upper DROP NOT NULL;
ALTER TABLE adversereaction_sort ALTER COLUMN lower DROP NOT NULL;
ALTER TABLE adversereaction_sort ALTER COLUMN upper DROP NOT NULL;
ALTER TABLE substance_sort ALTER COLUMN lower DROP NOT NULL;
ALTER TABLE substance_sort ALTER COLUMN upper DROP NOT NULL;

create INDEX observation_content_subject_display on observation (( content ->'subject' ->>'display'));
create INDEX observation_content_name_text on observation (( content-> 'name' ->> 'text'));
create INDEX documentreference_content_subject_display on documentreference (( content ->'subject' ->>'display'));
create INDEX medicationstatement_content_patient_display on medicationstatement (( content ->'patient' ->>'display'));
create INDEX condition_content_subject_display on condition (( content ->'subject' ->>'display'));
create INDEX encounter_content_subject_display on encounter (( content ->'subject' ->>'display'));

DROP INDEX documentreference_search_string_on_value_idx;
DROP INDEX documentreference_sort_on_lower_idx;
DROP INDEX documentreference_sort_on_upper_idx;