package org.patientview.persistence.model.enums;

/**
 * Created by jamesr@solidstategroup.com
 * Created on 10/06/2015
 */
public enum QuestionTypes {
    ABDOMINAL_PAIN,
    COMPLICATION,
    FEELING,
    MASS_IN_TUMMY,
    NUMBER_OF_STOOLS_DAYTIME,
    NUMBER_OF_STOOLS_NIGHTTIME,
    OPEN_BOWELS,
    PRESENT_BLOOD,
    TOILET_TIMING,

    // IBD Control Questionnaire
    IBD_CONTROLLED_TWO_WEEKS,
    IBD_CONTROLLED_CURRENT_TREATMENT,
    IBD_NO_TREATMENT,
    IBD_TWO_WEEKS_BOWEL,
    IBD_MISS_PLANNED_ACTIVITIES,
    IBD_WAKE_UP,
    IBD_SIGNIFICANT_PAIN,
    IBD_LACKING_ENERGY,
    IBD_FEEL_ANXIOUS,
    IBD_NEED_CHANGE,
    IBD_ALTERNATIVE_DRUGS,
    IBD_ADJUST_TREATMENT,
    IBD_SIDE_EFFECTS,
    IBD_NEW_SYMPTOMS,
    IBD_OVERALL_CONTROL,

    // Heart Symptom Scores
    HEART_SWELLING,
    HEART_FATIGUE,
    HEART_SHORTNESS_OF_BREATH,
    HEART_SHORTNESS_OF_BREATH_SLEEP
}
